num1=int (input ('Enter first Number:'))
num2=int (input ('Enter second Number:'))
num3=int (input ('Enter third Number:'))
num4=int (input ('Enter forth Number:'))
num5=int (input ('Enter fifth Number:'))
list=[num1,num2,num3,num4,num5]
print("list=",list)
list.sort()
print('ascending order=',list)
list.remove(max(list))
print("Max Removed List=",list)
avg=sum(list)/len(list)
print("Average=",avg)